import { StyleSheet, Text, View, ScrollView } from 'react-native'
import React from 'react'
import { SafeAreaView } from 'react-native-safe-area-context'

export default function TOS() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
    <Text style={styles.title}>Tickr – Terms of Service</Text>
    <Text style={styles.date}>Last Updated: November 10, 2025</Text>

    <Text style={styles.section}>
        Welcome to Tickr (“the App”), developed and operated by Jared Gilbert (“we,” “us,” or “our”).
        By downloading, accessing, or using Tickr, you (“you” or “the user”) agree to these Terms of
        Service (“Terms”). If you do not agree, do not use the App.
    </Text>

    <Text style={styles.heading}>1. Purpose of the App</Text>
    <Text style={styles.section}>
        Tickr provides a countdown timer and related time-tracking functionality. It is designed for
        personal and non-sensitive use only.
    </Text>

    <Text style={styles.heading}>2. Prohibited Use</Text>
    <Text style={styles.section}>
        You agree not to use Tickr for the creation, transmission, or storage of:
        {"\n"}• Controlled Unclassified Information (CUI)
        {"\n"}• Classified or sensitive government data
        {"\n"}• Confidential, proprietary, or restricted information
        {"\n\n"}This app is not authorized for any official U.S. Government use involving CUI or classified
        material. All users are responsible for ensuring that no sensitive data is entered, transmitted,
        or stored through the app.
    </Text>

    <Text style={styles.heading}>3. Firebase Services</Text>
    <Text style={styles.section}>
        Tickr uses Google Firebase services, including but not limited to:
        {"\n"}• Firebase Authentication
        {"\n"}• Firebase Firestore / Realtime Database
        {"\n"}• Firebase Analytics
        {"\n"}• Firebase Cloud Storage
        {"\n\n"}By using the App, you acknowledge and agree that your information may be processed and
        stored by Firebase in accordance with Google’s Privacy Policy and Firebase Terms of Service.
        We do not sell, rent, or share personal data for marketing purposes. However, usage data and
        technical information may be processed automatically through Firebase for security, analytics,
        and functionality purposes.
    </Text>

    <Text style={styles.heading}>4. Data Handling and Security</Text>
    <Text style={styles.section}>
        We take reasonable steps to secure your information, but:
        {"\n"}• We cannot guarantee absolute security of data transmitted over the Internet.
        {"\n"}• You acknowledge that you use Tickr at your own risk regarding data loss, breaches, or
        unauthorized access.
        {"\n\n"}You agree that by using this app, you consent to data being handled, processed, and stored
        through Firebase and related cloud services as necessary for app functionality.
    </Text>

    <Text style={styles.heading}>5. Disclaimer of Warranties</Text>
    <Text style={styles.section}>
        Tickr is provided “as is” and “as available,” without warranties of any kind, either express or
        implied. We make no warranties or representations about:
        {"\n"}• The accuracy or reliability of results or data generated by the app, or
        {"\n"}• The uninterrupted or error-free operation of the app.
        {"\n\n"}All use of the app is at your own discretion and risk.
    </Text>

    <Text style={styles.heading}>6. Limitation of Liability</Text>
    <Text style={styles.section}>
        To the fullest extent permitted by law:
        {"\n"}• We shall not be liable for any indirect, incidental, special, consequential, or punitive damages,
        including but not limited to loss of data, revenue, or profits.
        {"\n"}• In no event shall our total liability exceed the amount (if any) you paid to use the app.
        {"\n\n"}You expressly waive any right to bring claims, lawsuits, or legal action arising out of or relating
        to your use of Tickr.
    </Text>

    <Text style={styles.heading}>7. Indemnification</Text>
    <Text style={styles.section}>
        You agree to defend, indemnify, and hold harmless Jared Gilbert and any affiliates or service
        providers from any claims, losses, damages, liabilities, or expenses (including legal fees) arising
        out of your use or misuse of Tickr or violation of these Terms.
    </Text>

    <Text style={styles.heading}>8. Modifications</Text>
    <Text style={styles.section}>
        We reserve the right to modify or update these Terms at any time. Continued use of the app after
        such changes constitutes your acceptance of the revised Terms.
    </Text>

    <Text style={styles.heading}>9. Termination</Text>
    <Text style={styles.section}>
        We may suspend or terminate your access to Tickr at any time, with or without notice, for any
        reason, including suspected misuse or violation of these Terms.

    </Text>

    <Text style={styles.heading}>10. Governing Law</Text>
    <Text style={styles.section}>
        These Terms are governed by and construed in accordance with the laws of the State of Florida,
        United States, without regard to its conflict of law principles.
    </Text>

    <Text style={styles.heading}>11. Contact Information</Text>
    <Text style={styles.section}>
        For any questions regarding these Terms, you may contact:
        {"\n\n"}Jared Gilbert
        {"\n"}Email: jgilbert6867@gmail.com
        {"\n"}Developer of Tickr
    </Text>

    <Text style={styles.footer}>
        By using Tickr, you agree not to use it for any CUI or classified material, that data may be processed
        through Firebase under Google’s terms, and that you accept full responsibility for your use. The
        developer is not liable for any damages arising from use of the app.
    </Text>
    </ScrollView>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  content: {
    padding: 20,
    paddingBottom: 60,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 10,
  },
  date: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
    color: '#666',
  },
  heading: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 8,
  },
  section: {
    fontSize: 15,
    lineHeight: 22,
    color: '#333',
    width: '95%',
  },
  footer: {
    fontSize: 13,
    color: '#555',
    marginTop: 30,
    textAlign: 'center',
  },
})
